---
name: build maven workflow
on:
  push:
    branches: master
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4
      - name: Install java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: build the java code
        run: mvn clean install package
